# Generated by Django 4.1.1 on 2023-03-02 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("price", models.BigIntegerField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("ACEH", "Aceh"),
                            ("SUMUT", "Sumatera Utara"),
                            ("SUMBAR", "Sumatera Barat"),
                            ("RIAU", "Riau"),
                            ("JAMBI", "Jambi"),
                            ("SUMSEL", "Sumatera Selatan"),
                            ("BENGKULU", "Bengkulu"),
                            ("LAMPUNG", "Lampung"),
                            ("BABEL", "Kepulauan Bangka Belitung"),
                            ("KEP. RIAU", "Kepulauan Riau"),
                            ("DKI JAKARTA", "DKI Jakarta"),
                            ("JAWA BARAT", "Jawa Barat"),
                            ("JAWA TENGAH", "Jawa Tengah"),
                            ("DI YOGYAKARTA", "DI Yogyakarta"),
                            ("JAWA TIMUR", "Jawa Timur"),
                            ("BANTEN", "Banten"),
                            ("BALI", "Bali"),
                            ("NTB", "Nusa Tenggara Barat"),
                            ("NTT", "Nusa Tenggara Timur"),
                            ("KALBAR", "Kalimantan Barat"),
                            ("KALTENG", "Kalimantan Tengah"),
                            ("KALSEL", "Kalimantan Selatan"),
                            ("KALTIM", "Kalimantan Timur"),
                            ("KALTARA", "Kalimantan Utara"),
                            ("SULUT", "Sulawesi Utara"),
                            ("SULTENG", "Sulawesi Tengah"),
                            ("SULSEL", "Sulawesi Selatan"),
                            ("SULTRA", "Sulawesi Tenggara"),
                            ("GORONTALO", "Gorontalo"),
                            ("SULBAR", "Sulawesi Barat"),
                            ("MALUKU", "Maluku"),
                            ("MALUT", "Maluku Utara"),
                            ("PAPUA", "Papua"),
                            ("PAPUA BARAT", "Papua Barat"),
                        ],
                        max_length=50,
                    ),
                ),
                ("lng", models.FloatField()),
                ("lat", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Destination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.city"
                    ),
                ),
            ],
        ),
    ]
