# Generated by Django 4.1.1 on 2023-03-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="is_offline",
            field=models.BooleanField(default=True),
        ),
    ]
