# Generated by Django 4.1.1 on 2023-03-02 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
