# Generated by Django 4.1.1 on 2023-03-02 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0003_booking_is_offline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("BOOKED", "Booked"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                ],
                max_length=50,
            ),
        ),
    ]
