# Generated by Django 4.1.1 on 2023-03-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("travel", "0004_alter_booking_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="image",
            field=models.ImageField(
                default="city_images/default.jpg", upload_to="city_images"
            ),
        ),
        migrations.AddField(
            model_name="destination",
            name="image",
            field=models.ImageField(
                default="destination_images/default.jpg", upload_to="destination_images"
            ),
        ),
    ]
