# Generated by Django 4.1.7 on 2023-02-27 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phoneNumber', models.BigIntegerField()),
                ('photoURL', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
