# Generated by Django 4.1.1 on 2023-03-01 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("travel", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SellerModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("displayName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=50, unique=True)),
                ("phoneNumber", models.BigIntegerField()),
                ("address", models.TextField()),
                ("rating", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TravelerModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                ("uang", models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="TourGuideModel",
            fields=[
                (
                    "id",
                    models.CharField(max_length=500, primary_key=True, serialize=False),
                ),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="travel.city"
                    ),
                ),
            ],
        ),
    ]
