# Generated by Django 4.1.1 on 2023-03-02 11:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="travelermodel",
            old_name="uang",
            new_name="money",
        ),
    ]
