# Generated by Django 4.1.1 on 2023-02-27 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserModel',
            new_name='TravelerModel',
        ),
    ]
