# Generated by Django 4.1.1 on 2023-02-27 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_usermodel_travelermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelermodel',
            name='photoURL',
        ),
    ]
