# Generated by Django 4.1.1 on 2023-03-04 09:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_uang_travelermodel_money"),
    ]

    operations = [
        migrations.AddField(
            model_name="tourguidemodel",
            name="name",
            field=models.CharField(default="eugenius", max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tourguidemodel",
            name="photo_url",
            field=models.URLField(default="https://www.google.com"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="travelermodel",
            name="money",
            field=models.BigIntegerField(default=1000000),
        ),
    ]
