# Generated by Django 4.1.1 on 2023-03-03 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_rename_uang_travelermodel_money"),
    ]

    operations = [
        migrations.AlterField(
            model_name="travelermodel",
            name="money",
            field=models.BigIntegerField(default=1000000),
        ),
    ]
