# Generated by Django 4.1.1 on 2023-03-04 09:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_travelermodel_money"),
        ("user", "0003_tourguidemodel_name_tourguidemodel_photo_url_and_more"),
    ]

    operations = []
