# Generated by Django 4.1.1 on 2023-02-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_travelermodel_photourl'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phoneNumber', models.BigIntegerField()),
                ('address', models.TextField(default='Address')),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TourGuideModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('displayName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('phoneNumber', models.BigIntegerField()),
                ('address', models.TextField(default='Address')),
            ],
        ),
    ]
