# Generated by Django 4.1.1 on 2023-02-27 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_sellermodel_tourguidemodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellermodel',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tourguidemodel',
            name='address',
            field=models.TextField(),
        ),
    ]
